version: "1.0"
services:
    postgres:
        image: postgres:14.1-alpine
        environment: 
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        ports: 
            - "5432:5432"

#    mongodb:
#        image: mongo
#        container_name: mongodb
#        ports:
#            - "27017:27017"

    web:
        build: .
        command: bash -c "
            python manage.py migrate
            && python manage.py loaddata fixtures/admin.json
            && python manage.py runserver 0.0.0.0:8000"
        volumes:
            - .:/code
        ports:
            - "8000:8000"
        depends_on:
            - postgres